x-args: &args
  STEAMCMD_VERSION: $STEAMCMD_VERSION
  PALSERVER_DIR: &palserver-dir /home/steam/Steam/steamapps/common/PalServer
x-service: &service
  environment:
    TINI_KILL_PROCESS_GROUP: 1
  init: true
  volumes:
    - type: volume
      source: palserver
      target: *palserver-dir
services:
  steamcmd:
    <<: *service
    build:
      args:
        <<: *args
      target: steamcmd
    restart: on-failure:3
  palserver:
    <<: *service
    build:
      args:
        <<: *args
        RCON_PORT: $RCON_PORT
    command: $COMMAND
    depends_on:
      steamcmd:
        condition: service_completed_successfully
    ports:
      - "$PALSERVER_PORT:$PALSERVER_PORT/udp"
    restart: on-failure
  rcon: &rcon
    command:
    entrypoint: /rcon -a palserver:$RCON_PORT -p "$ADMIN_PASSWORD"
    image: outdead/rcon$RCON_VERSION
    profiles: [rcon]
  doexit:
    <<: *rcon
    command: Save DoExit
    profiles: [doexit]
volumes:
  palserver: